== General Information
* https://kind.sigs.k8s.io[Website]
* https://github.com/kubernetes-sigs/kind/[Open Source on Github]
* https://landscape.cncf.io/?selected=kind[Kind in CNCF (Cloud Native Interactive Landscape)]

In general, a Kubernetes cluster is started with the help of Docker. After starting a Kind cluster:

----
$ docker container ps
CONTAINER ID   IMAGE                  COMMAND                  CREATED       STATUS       PORTS                       NAMES
4f94409d1b75   kindest/node:v1.21.1   "/usr/local/bin/entr…"   3 hours ago   Up 3 hours   127.0.0.1:45301->6443/tcp   democluster-control-plane
----

== Installation of Kind on Ubuntu in WSL2

* assumed already installed:
** Docker
** kubectl

=== Install Go
** download with wget from https://go.dev/dl/
** follow installation instructions for Linux at https://go.dev/doc/install

=== Install Kind
* see https://kind.sigs.k8s.io/docs/user/quick-start/#installing-from-release-binaries and copy file
kind to /usr/local/bin


=== First Usage
* create cluster with

[source, terminal]
----
$ kind create cluster --name democluster
Creating cluster "democluster" ...
 ✓ Ensuring node image (kindest/node:v1.21.1) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
Set kubectl context to "kind-democluster"
You can now use your cluster with:

kubectl cluster-info --context kind-democluster

Have a nice day! 👋
----

* the above sets kubectl context to "kind-democluster" so that all kubectl commands now target that cluster, see
"democluster" in front of the node here:

----
$ kubectl get nodes
NAME                        STATUS   ROLES                  AGE     VERSION
democluster-control-plane   Ready    control-plane,master   5m33s   v1.21.1
----

* contexts are managed in /home/user/.kube/config
* other contexts:
----
$ kubectl config get-contexts
CURRENT   NAME               CLUSTER            AUTHINFO           NAMESPACE
*         kind-democluster   kind-democluster   kind-democluster
----
* switch between contexts:
----
$ kubectl config use-context kind-democluster
----

== Useful Kind-commands
----
$ kind -h
$ kind get clusters
$ kind create cluster --name cluster-to-delete
$ kind delete cluster --name cluster-to-delete
$ kind get nodes
----

== Configuration
=== Multi-Node Cluster
Cluster-creation can be configured via yaml-file, see https://kind.sigs.k8s.io/docs/user/configuration/[here], for
example multi-node cluster like this:

.multi-node-config.yaml
[source, yaml]
----
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: multi-node-cluster
nodes:
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker
----

----
$ kind create cluster --config multi-node-config.yaml
----

Created nodes:

----
$ kind get nodes --name multi-node-cluster
multi-node-cluster-worker3
multi-node-cluster-worker2
multi-node-cluster-control-plane
multi-node-cluster-worker
----

== Ingress Configuration
* goal: reaching cluster from localhost

=== Extra Port Mappings
See https://kind.sigs.k8s.io/docs/user/configuration/#extra-port-mappings[kind documentation here].

First, establish nothing is running on localhost:80:
----
$ curl localhost
curl: (52) Empty reply from server
----

Create cluster with extra port mappings:

.config-with-port-mapping.yaml
[source, yaml]
----
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cluster-with-port-mapping
nodes:
  - role: control-plane
    # port forward 80 on the host to 80 on this node
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        # optional: set the bind address on the host
        # 0.0.0.0 is the current default
        listenAddress: "127.0.0.1"
        # optional: set the protocol to one of TCP, UDP, SCTP.
        # TCP is the default
        protocol: TCP

----

----
$ kind create cluster --config config-with-port-mapping.yaml
----

Create pod that simply returns some text on port 80:

.simple-http-pod.yaml
[source,yaml]
----
kind: Pod
apiVersion: v1
metadata:
  name: foo
spec:
  containers:
    - name: foo
      image: hashicorp/http-echo:0.2.3
      args:
        - "-text=foo"
      ports:
        - containerPort: 5678
          hostPort: 80
----

----
$ kubectl apply -f simple-http-pod.yaml
----

Check localhost again:

----
$ curl localhost
foo
----

=== NodePort with Port Mappings
See https://kind.sigs.k8s.io/docs/user/configuration/#nodeport-with-port-mappings[kind documentation here].

First, establish nothing is running on localhost:80:
----
$ curl localhost
curl: (52) Empty reply from server
----

Create cluster with extra port mappings:

.config-with-port-mapping-2.yaml
[source, yaml]
----
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30950
    hostPort: 80
----

----
$ kind create cluster --config config-with-port-mapping-2.yaml
----

Create pod and NodePort service that forwards the container's port 5678 to the node port 30950 which is mapped to host's port 80 by the port mapping in config-with-port-mapping-2.yaml above:

.simple-http-pod-and-nodeport-service.yaml
[source,yaml]
----
kind: Pod
apiVersion: v1
metadata:
  name: foo
  labels:
    app: foo
spec:
  containers:
  - name: foo
    image: hashicorp/http-echo:0.2.3
    args:
    - "-text=foo"
    ports:
    - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: foo
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30950
    port: 5678
  selector:
    app: foo
----

----
$ kubectl apply -f simple-http-pod-and-nodeport-service.yaml
----

*IMPORTANT*: Kind node's _containerPort_ has to be to equal the service's _nodePort_! In this example, this is port 30950.

Check localhost again:

----
$ curl localhost
foo
----

== Sources
* https://kind.sigs.k8s.io[Kind Homepage]
* https://www.youtube.com/watch?v=m-IlbCgSzkc[How to run Kubernetes locally with Kind, That DevOps Guy, YouTube,
10:48.], shows installation and examples

